### ISSUE TITLE
PHP 5.3

### ISSUE THREAD

**Issue by mbartok** [jakubzapletal/bank-statements#4]
Is there a specific reason to use PHP 5.4 as dependency? With PHP 5.3 it would be more versatile, especially if the application is running on obsolete hosting.

**Comment by jakubzapletal** [comment]
I think nothing specific but `[]` instead of `array()`. Because PHP 5.3 is nearly 2 years without active support and 1 year security fixes only support it's better to move forward. But in case of demand I can downgrade to 5.3.

**Comment by mbartok** [comment]
i totally agree, but what can i do when my app is hosted on obsolete php 5.3? if you could downgrade to php 5.3 cust by replacing [] to array(), it would make my life sooo much easier.

**Comment by jakubzapletal** [comment]
I am already working on it :-) It will be done this night.
