### ISSUE TITLE
fix composer dependency

### ISSUE THREAD

**Issue by rebendajirijr** [jakubzapletal/bank-statements#9]
Problem:
- Installation request for satooshi/php-coveralls dev-master -> satisfiable by satooshi/php-coveralls[dev-master].
- satooshi/php-coveralls dev-master requires php >=5.5 -> your PHP version (5.3.29) or "config.platform.php" value does not satisfy that requirement

Details can be found at [Travis CI](https://travis-ci.org/jakubzapletal/bank-statements/builds/120061517).

**Comment by jakubzapletal** [comment]
Solved

**Comment by jakubzapletal** [comment]
Thank you for a contribution.
